const CHECKPOINTS = [
  {
    id: 0,
    digit: 4,
    title: "Норминнет-Детектив",
    location: "Опенспейс с ARM-компьютерами",
    codeComment: "// Получен новый запрос от агента...",
    codeLine: 'const <span class="variable">mission</span> = <span class="function">decode</span>(<span class="string">"latest-transmission"</span>);',
    riddle: "Ищи то, что краснеет от ошибок, но не имеет сердца. Найди компьютер, чей номер делится на 7, или постер с фейковой ошибкой Norminette.",
    hint: "ARM-компьютеры в главном опенспейсе. Ищи наклейку под клавиатурой или на столбе рядом с конкретным терминалом.",
    nextHint: "Следующая цель — комната с экраном, где проверяют код вместе.",
    emoji: "🔍",
  },
  {
    id: 1,
    digit: 2,
    title: "P2P Переговорка",
    location: "Большая переговорка с телевизором",
    codeComment: "// Узел связи найден. Шифруем данные...",
    codeLine: 'const <span class="variable">peer</span> = <span class="keyword">await</span> <span class="function">establishConnection</span>(<span class="string">"room-p2p"</span>);',
    riddle: "Я не учитель, но проверяю твой код. Я не друг, но спасаю от отчисления. Найди комнату, названную в честь этого принципа.",
    hint: "Большая переговорка с телевизором. Peer-to-Peer. Ищи QR на двери или рядом с экраном.",
    nextHint: "Дальше — туда, где автомат выдаёт топливо для дедлайнов.",
    emoji: "🤝",
  },
  {
    id: 2,
    digit: 1,
    title: "Зона Кофеина",
    location: "Автомат с кофе в холе",
    codeComment: "// Пополнение энергии...",
    codeLine: 'const <span class="variable">fuel</span> = <span class="function">brew</span>(<span class="string">"dark-roast"</span>, { temperature: <span class="number">96</span> });',
    riddle: "Топливо для дедлайнов. Ищи там, где автомат выдаёт чёрное зелье, а баги начинают казаться фичами.",
    hint: "Автомат с кофе в холе. QR-код спрятан на боковой стенке автомата, рядом с кнопками или на стене над ним.",
    nextHint: "Теперь ищи место, где исчезает время и здравый смысл.",
    emoji: "☕",
  },
  {
    id: 3,
    digit: 3,
    title: "Чёрная Дыра",
    location: "Тихая зона / Угол кампуса",
    codeComment: "// Внимание: аномалия обнаружена",
    codeLine: 'const <span class="variable">anomaly</span> = <span class="function">detect</span>({ type: <span class="string">"spacetime-distortion"</span> });',
    riddle: "Место, где исчезает время, дедлайны и здравый смысл. Найди горизонт событий.",
    hint: "Тихая зона или тёмный угол кампуса. Ищи постер с чёрной дырой на стене — QR-код в центре.",
    nextHint: "Последний рубеж — найди главное лого кампуса.",
    emoji: "🕳️",
  },
  {
    id: 4,
    digit: 0,
    title: "Сердце Кампуса",
    location: "Ресепшн / Стена с логотипом",
    codeComment: "// Финальный коммит. Цель — рядом.",
    codeLine: 'const <span class="variable">mission</span> = <span class="keyword">await</span> <span class="function">deploy</span>(<span class="string">"production"</span>);',
    riddle: "Финальный коммит. Найди главное лого кампуса и сделай с ним селфи.",
    hint: "Ресепшн или стена с логотипом. QR-код за стойкой или на самом логотипе.",
    nextHint: "Все коммиты собраны! Беги к организатору.",
    emoji: "💻",
  },
];
